name: Build Windows Executable

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --icon=assets/icons/app_icon.ico --name=CMYK_Analyzer run_gui.py
        
    - name: Create Windows deployment package
      run: |
        mkdir deploy_windows
        copy dist\CMYK_Analyzer.exe deploy_windows\
        if exist assets\icons\app_icon.ico copy assets\icons\app_icon.ico deploy_windows\
        cd deploy_windows
        powershell Compress-Archive -Path * -DestinationPath CMYK_Analyzer_Windows.zip
        cd ..
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          dist/CMYK_Analyzer.exe
          deploy_windows/
        retention-days: 30
        
    - name: Show build info
      run: |
        echo "Build completed successfully!"
        echo "Executable size:"
        dir dist\CMYK_Analyzer.exe
        echo "Deployment package contents:"
        dir deploy_windows\
